name: Deploy to Snowflake

on:
  push:
    paths:
      - 'snowflake_config/**'  # Déclenche le workflow pour chaque modification dans le dossier snowflake_config
      - 'my_dbt_project/**'    # Idem pour my_dbt_project
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install dbt-core dbt-snowflake

      - name: Create profiles.yml for DBT
        run: |
          mkdir -p ~/.dbt
          echo "
          my_dbt_project:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: '${{ secrets.DBT_ACCOUNT }}'
                user: '${{ secrets.DBT_USER }}'
                password: '${{ secrets.DBT_PASSWORD }}'
                role: 'your_role'  # Remplace par le rôle approprié
                database: '${{ secrets.DBT_DATABASE }}'
                warehouse: 'your_warehouse'  # Remplace par l'entrepôt de calcul approprié
                schema: 'your_schema'  # Remplace par le schéma approprié
          " > ~/.dbt/profiles.yml

      - name: Run DBT to deploy changes to Snowflake
        run: |
          cd my_dbt_project
          dbt deps  # Installe les dépendances DBT
          dbt run --target prod  # Exécute les modèles DBT dans Snowflake
          
