name: SQLfluff pour my_dbt_project

on:
  push:
    paths:
      - 'my_dbt_project/**'  # Déclenche le workflow pour chaque modification dans le dossier snowflake_config

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint sqlfluff
    - name: Analysing the SQL code with sqlfluff
      run: |
        sqlfluff lint --dialect postgres my_dbt_project/**/**.sql
